yamabiko_driver:
  ros__parameters:
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    Hz: 40
    left_wheel_joint: "left_wheel_joint"
    right_wheel_joint: "right_wheel_joint"
    liner_vel_lim: 0.5
    liner_accel_lim: 0.5
    angular_vel_lim: 1.57
    angular_accel_lim: 1.57
    calculate_odom_from_ypspur: true
    publish_odom_tf: true
